# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 02:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('block_number', models.IntegerField()),
                ('nonce', models.IntegerField()),
                ('file', models.FileField(upload_to='documents/')),
                ('file_hash', models.CharField(max_length=64)),
                ('signature1', models.CharField(max_length=64)),
                ('signature2', models.CharField(max_length=64)),
                ('previous_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('private_key', models.CharField(max_length=64)),
                ('public_key', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('blocks', models.ManyToManyField(to='certification.Block')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification.Student'),
        ),
        migrations.AddField(
            model_name='block',
            name='validators',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification.Validator'),
        ),
    ]
