# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='private_key',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='student',
            name='public_key',
            field=models.CharField(max_length=3000),
        ),
    ]
