# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_auto_20170430_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='chain_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='validator',
            name='blocks',
            field=models.ManyToManyField(blank=True, to='certification.Block'),
        ),
    ]
