# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0004_auto_20170430_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
