# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0005_block_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='valid',
            new_name='validity',
        ),
    ]
