# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0006_auto_20170502_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='validity',
        ),
    ]
